language: c

before_install:
  - sudo apt-get update -q
  - sudo apt-get install -qq apt-transport-https python-docutils
  - curl https://repo.varnish-cache.org/debian/GPG-key.txt | sudo apt-key add -
  - echo "deb https://repo.varnish-cache.org/ubuntu/ precise varnish-3.0" | sudo tee /etc/apt/sources.list.d/varnish-cache.list
  - echo "deb-src https://repo.varnish-cache.org/ubuntu/ precise varnish-3.0" | sudo tee -a /etc/apt/sources.list.d/varnish-cache.list
  - sudo apt-get update -q
  - sudo apt-get install -qq varnish libvarnishapi-dev
  - wget http://download.redis.io/releases/redis-3.0.1.tar.gz
  - tar zxvf redis-*.tar.gz
  - cd redis-*
  - make
  - sudo make PREFIX="/usr/local" install
  - cd ..
  - wget --no-check-certificate https://github.com/redis/hiredis/archive/v0.13.1.zip -O hiredis-0.13.1.zip
  - unzip hiredis-*.zip
  - cd hiredis-*
  - make
  - sudo make PREFIX="/usr/local" install
  - sudo ldconfig
  - cd ..

before_script:
  - #apt-get source -q varnish
  - wget --no-check-certificate https://repo.varnish-cache.org/ubuntu/pool/varnish-3.0/v/varnish/varnish_3.0.7.orig.tar.gz
  - tar zxvf varnish_3.0.7.orig.tar.gz
  - rm -f varnish_3.0.7.orig.tar.gz
  - cd varnish*
  - ./configure
  - make
  - cd ..
  - ./autogen.sh
  - ./configure VARNISHSRC=varnish* VMODDIR=`pwd`
  - make

script:
  - make check

compiler:
  - clang
  - gcc
